
CFG_JSON_EXTENSION = '.cfg.json'
CFG_DOT_EXTENSION = '.cfg.dot'
CFG_PDF_EXTENSION = '.cfg.pdf'

FV_ENV_VAR = 'FUZZVIEW_DIR'
LLVM_ENV_VAR = 'LLVM_HOME'
NICE_JSON_ENV_VAR = 'FV_NICE_JSON'

NODE_CHAR  = '#'
EMPTY_CHAR = ' '
CALL_CHAR  = '-'
IN_EDGE_CHAR  = '.'
OUT_EDGE_CHAR = '\''
